### ISSUE TITLE
Will this work on the TTGO T Beam V1?

### ISSUE THREAD

**Issue by danielforster** [kizniche/ttgo-tbeam-sensor-node-bme280#3]
Hi,

I am using the ttgo-tbeam-ttn-tracker that you put on Github and really enjoy it, many thanks :-). I would now like to upgrade to use the BME280 as per this Github project. Will this work OK on the V1 of the TTGO T Beam (I note that in the ttgo-tbeam-ttn-tracker there is the option to change from a TTGO T Beam v.7 to V1, but not in this code)?

Cheers and thanks again,

Daniel

**Comment by kizniche** [comment]
It is incompatible with v1

**Comment by danielforster** [comment]
Wonderful, cheers for coming back so fast, and again, cheers for such a briliant piece of code. - Dan
